// File generated from our OpenAPI spec by Stainless. See CONTRIBUTING.md for details.

package cmd

import (
	"context"
	"fmt"

	"github.com/dedalus-labs/dedalus-sdk-go"
	"github.com/dedalus-labs/dedalus-sdk-go/option"
	"github.com/stainless-sdks/dedalus-sdk-cli/internal/apiquery"
	"github.com/stainless-sdks/dedalus-sdk-cli/internal/requestflag"
	"github.com/tidwall/gjson"
	"github.com/urfave/cli/v3"
)

var imagesCreateVariation = cli.Command{
	Name:    "create-variation",
	Usage:   "Create variations of an image.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "image",
			Required:  true,
			BodyPath:  "image",
			FileInput: true,
		},
		&requestflag.Flag[*string]{
			Name:     "model",
			Default:  requestflag.Ptr[string]("openai/dall-e-2"),
			BodyPath: "model",
		},
		&requestflag.Flag[*int64]{
			Name:     "n",
			Default:  requestflag.Ptr[int64](1),
			BodyPath: "n",
		},
		&requestflag.Flag[*string]{
			Name:     "response-format",
			Default:  requestflag.Ptr[string]("url"),
			BodyPath: "response_format",
		},
		&requestflag.Flag[*string]{
			Name:     "size",
			Default:  requestflag.Ptr[string]("1024x1024"),
			BodyPath: "size",
		},
		&requestflag.Flag[*string]{
			Name:     "user",
			BodyPath: "user",
		},
	},
	Action:          handleImagesCreateVariation,
	HideHelpCommand: true,
}

var imagesEdit = cli.Command{
	Name:    "edit",
	Usage:   "Edit images using inpainting.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:      "image",
			Required:  true,
			BodyPath:  "image",
			FileInput: true,
		},
		&requestflag.Flag[string]{
			Name:     "prompt",
			Required: true,
			BodyPath: "prompt",
		},
		&requestflag.Flag[*string]{
			Name:      "mask",
			BodyPath:  "mask",
			FileInput: true,
		},
		&requestflag.Flag[*string]{
			Name:     "model",
			Default:  requestflag.Ptr[string]("openai/dall-e-2"),
			BodyPath: "model",
		},
		&requestflag.Flag[*int64]{
			Name:     "n",
			Default:  requestflag.Ptr[int64](1),
			BodyPath: "n",
		},
		&requestflag.Flag[*string]{
			Name:     "response-format",
			Default:  requestflag.Ptr[string]("url"),
			BodyPath: "response_format",
		},
		&requestflag.Flag[*string]{
			Name:     "size",
			Default:  requestflag.Ptr[string]("1024x1024"),
			BodyPath: "size",
		},
		&requestflag.Flag[*string]{
			Name:     "user",
			BodyPath: "user",
		},
	},
	Action:          handleImagesEdit,
	HideHelpCommand: true,
}

var imagesGenerate = cli.Command{
	Name:    "generate",
	Usage:   "Generate images from text prompts.",
	Suggest: true,
	Flags: []cli.Flag{
		&requestflag.Flag[string]{
			Name:     "prompt",
			Usage:    "A text description of the desired image(s). The maximum length is 32000 characters for `gpt-image-1`, 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.",
			Required: true,
			BodyPath: "prompt",
		},
		&requestflag.Flag[*string]{
			Name:     "background",
			Usage:    "Allows to set transparency for the background of the generated image(s).\nThis parameter is only supported for `gpt-image-1`. Must be one of\n`transparent`, `opaque` or `auto` (default value). When `auto` is used, the\nmodel will automatically determine the best background for the image.\n\nIf `transparent`, the output format needs to support transparency, so it\nshould be set to either `png` (default value) or `webp`.",
			BodyPath: "background",
		},
		&requestflag.Flag[*string]{
			Name:     "model",
			Usage:    "The model to use for image generation. One of `openai/dall-e-2`, `openai/dall-e-3`, or `openai/gpt-image-1`. Defaults to `openai/dall-e-2` unless a parameter specific to `gpt-image-1` is used.",
			BodyPath: "model",
		},
		&requestflag.Flag[*string]{
			Name:     "moderation",
			Usage:    "Control the content-moderation level for images generated by `gpt-image-1`. Must be either `low` for less restrictive filtering or `auto` (default value).",
			BodyPath: "moderation",
		},
		&requestflag.Flag[*int64]{
			Name:     "n",
			Usage:    "The number of images to generate. Must be between 1 and 10. For `dall-e-3`, only `n=1` is supported.",
			BodyPath: "n",
		},
		&requestflag.Flag[*int64]{
			Name:     "output-compression",
			Usage:    "The compression level (0-100%) for the generated images. This parameter is only supported for `gpt-image-1` with the `webp` or `jpeg` output formats, and defaults to 100.",
			BodyPath: "output_compression",
		},
		&requestflag.Flag[*string]{
			Name:     "output-format",
			Usage:    "The format in which the generated images are returned. This parameter is only supported for `gpt-image-1`. Must be one of `png`, `jpeg`, or `webp`.",
			BodyPath: "output_format",
		},
		&requestflag.Flag[*int64]{
			Name:     "partial-images",
			Usage:    "The number of partial images to generate. This parameter is used for\nstreaming responses that return partial images. Value must be between 0 and 3.\nWhen set to 0, the response will be a single image sent in one streaming event.\n\nNote that the final image may be sent before the full number of partial images\nare generated if the full image is generated more quickly.",
			BodyPath: "partial_images",
		},
		&requestflag.Flag[*string]{
			Name:     "quality",
			Usage:    "The quality of the image that will be generated.\n\n- `auto` (default value) will automatically select the best quality for the given model.\n- `high`, `medium` and `low` are supported for `gpt-image-1`.\n- `hd` and `standard` are supported for `dall-e-3`.\n- `standard` is the only option for `dall-e-2`.",
			BodyPath: "quality",
		},
		&requestflag.Flag[*string]{
			Name:     "response-format",
			Usage:    "The format in which generated images with `dall-e-2` and `dall-e-3` are returned. Must be one of `url` or `b64_json`. URLs are only valid for 60 minutes after the image has been generated. This parameter isn't supported for `gpt-image-1` which will always return base64-encoded images.",
			BodyPath: "response_format",
		},
		&requestflag.Flag[*string]{
			Name:     "size",
			Usage:    "The size of the generated images. Must be one of `1024x1024`, `1536x1024` (landscape), `1024x1536` (portrait), or `auto` (default value) for `gpt-image-1`, one of `256x256`, `512x512`, or `1024x1024` for `dall-e-2`, and one of `1024x1024`, `1792x1024`, or `1024x1792` for `dall-e-3`.",
			BodyPath: "size",
		},
		&requestflag.Flag[*bool]{
			Name:     "stream",
			Usage:    "Generate the image in streaming mode. Defaults to `false`. See the\n[Image generation guide](https://platform.openai.com/docs/guides/image-generation) for more information.\nThis parameter is only supported for `gpt-image-1`.",
			BodyPath: "stream",
		},
		&requestflag.Flag[*string]{
			Name:     "style",
			Usage:    "The style of the generated images. This parameter is only supported for `dall-e-3`. Must be one of `vivid` or `natural`. Vivid causes the model to lean towards generating hyper-real and dramatic images. Natural causes the model to produce more natural, less hyper-real looking images.",
			BodyPath: "style",
		},
		&requestflag.Flag[*string]{
			Name:     "user",
			Usage:    "A unique identifier representing your end-user, which can help OpenAI to monitor and detect abuse. [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids).",
			BodyPath: "user",
		},
	},
	Action:          handleImagesGenerate,
	HideHelpCommand: true,
}

func handleImagesCreateVariation(ctx context.Context, cmd *cli.Command) error {
	client := githubcomdedaluslabsdedalussdkgo.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		MultipartFormEncoded,
		false,
	)
	if err != nil {
		return err
	}

	params := githubcomdedaluslabsdedalussdkgo.ImageNewVariationParams{}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Images.NewVariation(ctx, params, options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "images create-variation",
		Transform:      transform,
	})
}

func handleImagesEdit(ctx context.Context, cmd *cli.Command) error {
	client := githubcomdedaluslabsdedalussdkgo.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		MultipartFormEncoded,
		false,
	)
	if err != nil {
		return err
	}

	params := githubcomdedaluslabsdedalussdkgo.ImageEditParams{}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Images.Edit(ctx, params, options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "images edit",
		Transform:      transform,
	})
}

func handleImagesGenerate(ctx context.Context, cmd *cli.Command) error {
	client := githubcomdedaluslabsdedalussdkgo.NewClient(getDefaultRequestOptions(cmd)...)
	unusedArgs := cmd.Args().Slice()

	if len(unusedArgs) > 0 {
		return fmt.Errorf("Unexpected extra arguments: %v", unusedArgs)
	}

	options, err := flagOptions(
		cmd,
		apiquery.NestedQueryFormatBrackets,
		apiquery.ArrayQueryFormatComma,
		ApplicationJSON,
		false,
	)
	if err != nil {
		return err
	}

	params := githubcomdedaluslabsdedalussdkgo.ImageGenerateParams{}

	var res []byte
	options = append(options, option.WithResponseBodyInto(&res))
	_, err = client.Images.Generate(ctx, params, options...)
	if err != nil {
		return err
	}

	obj := gjson.ParseBytes(res)
	format := cmd.Root().String("format")
	explicitFormat := cmd.Root().IsSet("format")
	transform := cmd.Root().String("transform")
	return ShowJSON(obj, ShowJSONOpts{
		ExplicitFormat: explicitFormat,
		Format:         format,
		RawOutput:      cmd.Root().Bool("raw-output"),
		Title:          "images generate",
		Transform:      transform,
	})
}
